### ISSUE TITLE
'AlignedSegment' is not a type identifier

### ISSUE THREAD

**Issue by 25shmeckles** [sein-tao/bam2m5#1]
This happens when trying to install with:
Python 3.8.2
Cython 0.29.15

```
python cython_build.py
   
Compiling cbam2m5.pyx because it changed.
[1/1] Cythonizing cbam2m5.pyx
/Users/user1/anaconda/envs/Laptop/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/user1/MEGA/Laptop/Laptop/extras/bam2m5/cbam2m5.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import print_function
nargs = 4
from cigar import CIGAR, cigartuple
from BioUtil import samFile, xzopen, cachedFasta

from pysam.calignmentfile cimport AlignmentFile, AlignedSegment
^
------------------------------------------------------------

cbam2m5.pyx:17:0: 'pysam/calignmentfile.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import print_function
nargs = 4
from cigar import CIGAR, cigartuple
from BioUtil import samFile, xzopen, cachedFasta

from pysam.calignmentfile cimport AlignmentFile, AlignedSegment
^
------------------------------------------------------------

cbam2m5.pyx:17:0: 'pysam/calignmentfile/AlignmentFile.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from __future__ import print_function
nargs = 4
from cigar import CIGAR, cigartuple
from BioUtil import samFile, xzopen, cachedFasta

from pysam.calignmentfile cimport AlignmentFile, AlignedSegment
^
------------------------------------------------------------

cbam2m5.pyx:17:0: 'pysam/calignmentfile/AlignedSegment.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
        score += self.gap_extend * (cigar_len[CIGAR.INS] + cigar_len[CIGAR.DEL])
        return int(score)

# m5 fileds
# qName qLength qStart qEnd qStrand tName tLength tStart tEnd tStrand score numMatch numMismatch numIns numDel mapQV qAlignedSeq matchPattern tAlignedSeq
def bam2m5(AlignedSegment rec, object fa, dict ref_lengths, object score_scheme):
          ^
------------------------------------------------------------

cbam2m5.pyx:38:11: 'AlignedSegment' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            rec.mapping_quality,
            qseq, mp, rseq,
            )


cdef padding_seq(str qseq, str rseq, AlignedSegment rec):
                                    ^
------------------------------------------------------------

cbam2m5.pyx:81:37: 'AlignedSegment' is not a type identifier
Traceback (most recent call last):
  File "cython_build.py", line 17, in <module>
    ext_modules = cythonize(extension)
  File "/Users/user1/anaconda/envs/Laptop/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1101, in cythonize
    cythonize_one(*args)
  File "/Users/user1/anaconda/envs/Laptop/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1224, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cbam2m5.pyx
```

**Comment by 25shmeckles** [comment]
solved by replacing `from pysam.calignmentfile cimport AlignmentFile, AlignedSegment` with `from pysam.libcalignmentfile cimport AlignmentFile, AlignedSegment` in `cbam2m5.pyx`
